In [ ]:
#Importing the Dataset
import pandas as pd
# Replace '/path/to/your/uploaded/file/SMSSpamCollection' with the actual path to your file in Colab
messages = pd.read_csv('/content/SMSSpamCollection.txt',sep ='\t',names = ["label","message"])

In [ ]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
messages.shape

(5572, 2)

In [ ]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [ ]:
# Data Cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
corpus = []
for i in range (0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [ ]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [ ]:
from gensim.utils import simple_preprocess
simple_preprocess(corpus[0])

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [ ]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

words = []
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'reward',
  

In [ ]:
import gensim

In [ ]:
## Lets train Word2Vec from scratch
model = gensim.models.Word2Vec(words,window=5,min_count = 2)

In [ ]:
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'want',
 'good',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'stop',
 'see',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'still',
 'tell',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'hi',
 'say',
 'work',
 'new',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'messag',
 'dear',
 'night',
 'happi',
 'wait',
 'well',
 'give',
 'thing',
 'tri',
 'great',
 'much',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'friend',
 'thank',
 'way',
 'ye',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'tone',
 'care',
 'cash',
 'said',
 'amp',
 'im',
 'leav',
 'yeah',
 'realli',
 'find',
 'babe',
 'life',
 'morn',
 'last',
 'sleep',
 'keep',
 'uk',
 'year',
 'servic',
 'nokia',
 'sure',
 'anyth',
 'com',
 'buy',
 'use',
 'would',
 'start',
 'contact',

In [ ]:
model.corpus_count

5564

In [ ]:
model.epochs

5

In [ ]:
model.wv.similar_by_word('kid')

[('amp', 0.9981095790863037),
 ('use', 0.9981095194816589),
 ('im', 0.9981041550636292),
 ('big', 0.9980655312538147),
 ('guess', 0.9980632662773132),
 ('oh', 0.9980460405349731),
 ('live', 0.9980450868606567),
 ('back', 0.9980354905128479),
 ('place', 0.9980339407920837),
 ('give', 0.9980313181877136)]

In [ ]:
model.wv['kid'].shape

(100,)

In [ ]:
def avg_word2vec(doc):
  # remove out-of-vocabulary words
  #sent = [word for word in doc if word in model .wv.index_to_key]
  #print(sent)
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis = 0)
         #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [ ]:
!pip install tqdm

In [ ]:
from tqdm import tqdm

In [ ]:
type(model.wv.index_to_key)

list

In [ ]:
#apply for the entire sentences
import numpy as np
X = []
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

  6%|▋         | 352/5564 [00:00<00:01, 3515.17it/s]/usr/local/lib/python3.12/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5564/5564 [00:01<00:00, 3891.07it/s]


In [ ]:
type(X)

list

In [ ]:
X_new = np.array(X, dtype=object)

In [ ]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [ ]:
X_new[1]

array([-0.18919504,  0.17232414,  0.02434771,  0.00460022,  0.08436216,
       -0.29847226,  0.11572387,  0.36220777, -0.13658723, -0.13035586,
       -0.13855633, -0.27165663, -0.08280184,  0.01900885,  0.08349662,
       -0.12123547,  0.00746799, -0.19991983,  0.02038558, -0.36637193,
        0.13080463,  0.16404897,  0.03765777, -0.07943909, -0.04576617,
        0.0260127 , -0.22549948, -0.18654358, -0.18337294,  0.07455043,
        0.24948427,  0.06259127,  0.0329749 , -0.10628903, -0.14223133,
        0.227216  , -0.03606966, -0.17765239, -0.03388391, -0.3557712 ,
        0.05905085, -0.16215411, -0.03691094,  0.03334544,  0.18482791,
       -0.11358882, -0.16254702, -0.01414112,  0.13650344,  0.18129337,
        0.06019236, -0.20341487, -0.06086405,  0.01889947, -0.14221619,
        0.12236202,  0.10532661, -0.00884591, -0.25686818,  0.03852952,
        0.03958693,  0.15487394, -0.10463045, -0.07111853, -0.22471818,
        0.0878204 ,  0.05053697,  0.12420386, -0.17150006,  0.21

In [ ]:
X_new[5]

array([-0.26147392,  0.24721326,  0.03486173,  0.00852996,  0.1098819 ,
       -0.41982365,  0.15496328,  0.5130964 , -0.19316012, -0.19192773,
       -0.20128296, -0.38041025, -0.11546589,  0.03195967,  0.11463743,
       -0.16889101,  0.01274742, -0.28151056,  0.03581996, -0.5181742 ,
        0.18538289,  0.23035169,  0.04816754, -0.11006065, -0.07048029,
        0.03448459, -0.3174232 , -0.26021418, -0.2581555 ,  0.10697879,
        0.34483716,  0.09113239,  0.03957868, -0.15298462, -0.19933201,
        0.32288608, -0.04965701, -0.25065398, -0.0544968 , -0.5029326 ,
        0.08088303, -0.22678074, -0.05085268,  0.05268459,  0.26098135,
       -0.15528382, -0.2314818 , -0.02407517,  0.19251081,  0.25779316,
        0.0842274 , -0.28523606, -0.08291647,  0.01896974, -0.1980788 ,
        0.1749127 ,  0.14989248, -0.00785291, -0.35997498,  0.05403191,
        0.06455527,  0.22176105, -0.14721271, -0.10065369, -0.31946993,
        0.12826201,  0.07723268,  0.1723429 , -0.24169116,  0.29

In [ ]:
##Assignment
## Train-Test-Split
##Apply to model

In [ ]:
# Creating a Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500, binary = True)
X = cv.fit_transform(corpus).toarray()

In [ ]:
X
X.shape

(5572, 2500)

In [ ]:
y = pd.get_dummies(messages['label'])
y=y.iloc[:,1].values
y

array([False, False,  True, ..., False, False, False])

In [ ]:
#Train-Test-Split
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [ ]:
#Prediction
y_pred = spam_detect_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report


In [ ]:
score = accuracy_score(y_test,y_pred)
score

0.9856502242152466

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       961
        True       0.93      0.97      0.95       154

    accuracy                           0.99      1115
   macro avg       0.96      0.98      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
#Creating the TFIDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range = (1,2))
X = tv.fit_transform(corpus).toarray()

In [ ]:
#Train_Test_Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)


In [ ]:
#Prediction
y_pred = spam_detect_model.predict(X_test)

In [ ]:
score = accuracy_score(y_test,y_pred)
score

0.97847533632287

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       1.00      0.98      0.99       979
        True       0.85      1.00      0.92       136

    accuracy                           0.98      1115
   macro avg       0.93      0.99      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

0.9847533632286996
              precision    recall  f1-score   support

       False       1.00      0.98      0.99       972
        True       0.89      1.00      0.94       143

    accuracy                           0.98      1115
   macro avg       0.95      0.99      0.97      1115
weighted avg       0.99      0.98      0.99      1115

